### ISSUE TITLE
Need Immediate help

### ISSUE THREAD

**Issue by ashhadahmd** [rayanarfawi/nuxt-test#25]
Hi there, if I am not wrong is this your post:

https://discourse.threejs.org/t/extrude-face-selection/20147/4

and if it is plz contact me back here's my discord: ashhad0001, I am very sorry to disturb you.

**Comment by rayanarfawi** [comment]
Hello , i am no longer developping , i will look through my hardisk and if
i find the project i will send it to you

**Comment by ashhadahmd** [comment]
Thank you for your instant reply my, really appreciate your time plz let me know if you find it thanks again

**Comment by ashhadahmd** [comment]
Sorry to disturb you again, any updates on the project?

Again pardon me urgency.

**Comment by rayanarfawi** [comment]
Bro it would take at least a week so i can find them , i have thousands of
projects

**Comment by ashhadahmd** [comment]
Is there a social where I can discuss the problem with you in-detail cause talking over a github issue is dumb. If you have discord we can talk on that.

**Comment by ashhadahmd** [comment]
Hello again, sorry for disturbing and intruding your personal space, but is it possible for you to share just the logic of extrusion, I am sure you are busy in your own personal matter, but the issue is that I require this function before Tuesday. Please try to understand my urgency and don't mind my repeated messages. Again I am sorry and also if you have a social we can discuss this matter there in detail rather then on a GitHub issue cause that feels silly.

Regards Ashhad.
